name: Deploy Project

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "02 Starting Project"
    steps:
      - name: Get code
        uses: actions/checkout@v7

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: "02 Starting Project/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
  -name: Deploy  
   runs-on: ubuntu-latest
    needs: test
      steps:
        - name: Get code
          uses: actions/checkout@v7
  
        - name: Install Node.js
          uses: actions/setup-node@v6
          with:
            node-version: 24
            cache: npm
            cache-dependency-path: "02 Starting Project/package-lock.json"
  
        - name: Install dependencies
          run: npm ci
  
        - name: Deploy to Production
          run: echo "Deploying to production..."


